# Generated by Django 5.2.1 on 2025-06-01 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created', verbose_name='Created')),
                ('modified', models.DateTimeField(blank=True, db_column='modified', null=True, verbose_name='Modified')),
                ('is_active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='is_active')),
                ('nombre', models.CharField(db_column='nombre', default='Nombre de la Empresa', help_text='Nombre de la Empresa', max_length=250, verbose_name='Nombre')),
                ('direccion', models.TextField(blank=True, db_column='direccion', help_text='Direccion de la Empresa', max_length=254, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, db_column='telefono', default='000-000-0000', help_text='Por favor ingrese el teléfono parecido al ejemplo', max_length=16, null=True, verbose_name='Teléfono')),
                ('contacto', models.CharField(db_column='contacto', help_text='Por favor ingrese el nombre del contacto', max_length=120, verbose_name='Nombre Contacto')),
                ('web', models.URLField(blank=True, db_column='web', help_text='Por favor ingrese la URL', null=True, verbose_name='Web')),
                ('created_by', models.ForeignKey(blank=True, db_column='create_by', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Create by')),
                ('modified_by', models.ForeignKey(blank=True, db_column='modified_by', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'distribuidora',
                'verbose_name_plural': 'distribuidoras',
                'db_table': 'Distribuidoras',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created', verbose_name='Created')),
                ('modified', models.DateTimeField(blank=True, db_column='modified', null=True, verbose_name='Modified')),
                ('is_active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='is_active')),
                ('nombre', models.CharField(db_column='nombre', default='Nombre de la Empresa', help_text='Nombre de la Empresa', max_length=250, verbose_name='Nombre')),
                ('direccion', models.TextField(blank=True, db_column='direccion', help_text='Direccion de la Empresa', max_length=254, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, db_column='telefono', default='000-000-0000', help_text='Por favor ingrese el teléfono parecido al ejemplo', max_length=16, null=True, verbose_name='Teléfono')),
                ('contacto', models.CharField(db_column='contacto', help_text='Por favor ingrese el nombre del contacto', max_length=120, verbose_name='Nombre Contacto')),
                ('web', models.URLField(blank=True, db_column='web', help_text='Por favor ingrese la URL', null=True, verbose_name='Web')),
                ('created_by', models.ForeignKey(blank=True, db_column='create_by', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Create by')),
                ('modified_by', models.ForeignKey(blank=True, db_column='modified_by', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'editorial',
                'verbose_name_plural': 'editoriales',
                'db_table': 'Editoriales',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created', verbose_name='Created')),
                ('modified', models.DateTimeField(blank=True, db_column='modified', null=True, verbose_name='Modified')),
                ('is_active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='is_active')),
                ('isbn', models.CharField(db_column='isbn', default='000000000-0', help_text='ISBN del Libro', max_length=20, verbose_name='ISBN')),
                ('titulo', models.CharField(db_column='titulo', default='Titulo', help_text='Titulo del Libro', max_length=200, verbose_name='Titulo')),
                ('autor', models.CharField(db_column='autor', default='Nombre Apellido', help_text='Autor del Libro', max_length=100, verbose_name='Autor')),
                ('publicacion', models.DateField(db_column='publicacion')),
                ('paginas', models.PositiveSmallIntegerField(db_column='paginas')),
                ('precio', models.DecimalField(db_column='precio', decimal_places=2, max_digits=6)),
                ('created_by', models.ForeignKey(blank=True, db_column='create_by', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Create by')),
                ('id_distribuidora', models.ForeignKey(db_column='distribuidora', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_distribuidora', to='modulo1.distribuidora', verbose_name='Distribuidora')),
                ('id_editorial', models.ForeignKey(db_column='editorial', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_editorial', to='modulo1.editorial', verbose_name='Editorial')),
                ('modified_by', models.ForeignKey(blank=True, db_column='modified_by', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'libro',
                'verbose_name_plural': 'libros',
                'db_table': 'Libros',
                'ordering': ['id'],
            },
        ),
    ]
